# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Load application settings. This is defines the site for DJR.
require 'yaml'
application = YAML.load_file 'settings.yml'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # With wily we get universe and multiverse to meet EMDB installation requirements.
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = application['vagrant_name']
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = application['vagrant_name']
  config.vm.network :private_network, ip: application['vagrant_ip']
  config.vm.define application['vagrant_name'] do |site|
  end

  config.vm.provision :ansible do |ansible|
    # ansible.verbose = "vvv"
    ansible.playbook = "ansible/playbook.yml"
    ansible.extra_vars = {
      vagrant_name: application['vagrant_name'],
      vagrant_ip: application['vagrant_ip'],
    }
  end

end

