---
- name: Prep for nginx
  yum:
     name: epel-release
     state: present

- name: Install nginx
  yum:
     name: nginx
     state: present

- name: Copy the nginx configuration
  copy:
    src: files/nginx/entermedia.conf
    dest: /etc/nginx/conf.d/entermedia.conf
    owner: root
    group: root
    mode: 0644

- name: Allow nginx proxy_pass to work
  command: setsebool -P httpd_can_network_connect true
  changed_when: false

- name: Restart nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
  changed_when: false
