---
- name: Install python pip
  yum:
     name: python-pip
     state: present

- name: Install httplib2 for ansible pip/uri support
  pip:
    name: httplib2

- name: Get an auth cookie
  uri:
    url: "http://{{ vagrant_ip }}/mediadb/services/authentication/login"
    method: POST
    body: "{{ lookup('file', 'files/json/login.json') }}"
    body_format: json
    HEADER_Content-Type: "application/json"
  register: do_login

- debug: msg="{{ do_login }}"

- name: Create an API user
  uri:
    url: "http://{{ vagrant_ip }}/mediadb/services/settings/users/create"
    method: POST
    body: "{{ lookup('file', 'files/json/create-api-user.json') }}"
    body_format: json
    HEADER_Cookie: "{{ do_login.set_cookie }}"
  register: do_api_user

- debug: msg="{{ do_api_user }}"

- name: Initialise the JSON api. Not sure why oir what this does exactly...
  uri:
    url: "http://{{ vagrant_ip }}/mediadb/views/actions/setupmodules.html"
    method: GET
    HEADER_Cookie: "{{ do_login.set_cookie }}"
  register: do_json_init

- debug: msg="{{ do_json_init}}"

# Ideally we have an 'api' role, but JSON api is weak on this,
# just make the api user an administrator.
- name: Add API user to role (post to html page)
  uri:
    url: "http://{{ vagrant_ip }}/emshare/views/settings/users/usermanager/user/editrole.html"
    method: POST
    body: "userid=api_user4&username=api_user&searchtype=userprofile&save=true&sourcepath=api_user&id=api_user&field=settingsgroup&settingsgroup.value=administrator"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    HEADER_Cookie: "{{ do_login.set_cookie }}"
  register: do_role

- debug: msg="{{ do_role }}"

- name: Create a project
  uri:
    url: "http://{{ vagrant_ip }}/mediadb/services/module/project/create"
    method: POST
    body: "{{ lookup('file', 'files/json/create-project.json') }}"
    body_format: json
    HEADER_Cookie: "{{ do_login.set_cookie }}"
  register: do_project

#- debug: msg="{{ do_project }}"
#- debug: msg="{{ Project created with id: do_project.json.data.id }}"

- name: Create a library
  uri:
    url: "http://{{ vagrant_ip }}/mediadb/services/module/library/create"
    method: POST
    body: "{{ lookup('file', 'files/json/create-library.json') }}"
    body_format: json
    HEADER_Cookie: "{{ do_login.set_cookie }}"
  register: do_library

#- debug: msg="{{ do_library }}"
#- debug: msg="{{ Project created with id: do_library.json.data.id }}"

