---
- name: Add additional repositories for openjdk
  shell: /usr/bin/add-apt-repository -y ppa:openjdk-r/ppa
  tags: apt

- name: Add EnterMediaDB's repository
  shell: /bin/echo "deb http://packages.entermediadb.org/repo/apt stable main" > /etc/apt/sources.list.d/entermediadb.list
  tags: apt

- name: Add key to EnterMediaDB's repository
  shell: /usr/bin/wget -O /etc/apt/trusted.gpg.d/entermediadb.gpg http://packages.entermediadb.org/repo/apt/entermediadb.gpg
  tags: apt

#- name: Open multiverse trusty options in sources.list
#  lineinfile: dest=/etc/apt/sources.list regexp="^deb .* trusty multiverse$" line="deb http://{{nameOSPackageRepositoryInstance}}.local/ubuntu/ trusty multiverse"
#  tags: apt
#
#- name: Open multiverse trusty src options in sources.list
#  lineinfile: dest=/etc/apt/sources.list regexp="^deb-src .* trusty multiverse$" line="deb-src http://{{nameOSPackageRepositoryInstance}}.local/ubuntu/ trusty multiverse"
#  tags: apt

#- name: Open multiverse trusty-updates options in sources.list
#  lineinfile: dest=/etc/apt/sources.list regexp="^deb .* trusty-updates multiverse$" line="deb http://{{nameOSPackageRepositoryInstance}}.local/ubuntu/ trusty-updates multiverse"
#  tags: apt
#
#- name: Open multiverse trusty-updates src options in sources.list
#  lineinfile: dest=/etc/apt/sources.list regexp="^deb-src .* trusty-updates multiverse$" line="deb-src http://{{nameOSPackageRepositoryInstance}}.local/ubuntu/ trusty-updates multiverse"
#  tags: apt

- name: Add universe repositories
  command: 'apt-add-repository universe'
  changed_when: false

- name: Add multiverse repositories
  command: 'apt-add-repository multiverse'
  changed_when: false

- name: Update apt-get repository
  apt: update_cache=yes
  tags: apt

############
# Install EnterMediaDB
- name: Install required EnterMediaDB packages
  apt: name={{item}} state=present
  with_items:
  - libpam-cracklib
  - entermediadb
  tags: apt

- name: Create user for entermediadb
  shell: if [ ! $(/bin/grep /home/{{item}} /etc/passwd) ]; then /usr/sbin/useradd -m -s /bin/bash {{item}}; fi
  with_items:
  - entermedia

- name: Configure default instance of entermediadb
  shell: /bin/echo -e "\n\n\ny\n" | /usr/bin/entermediadb install
  