---
#- name: Install Guest additions
#  apt:
#    name: virtualbox-guest-additions-iso
#    state: present

- name: Install various tools
  apt: name={{item}} state=installed
  with_items:
    - lynx
    - vim
