---
# These additions not needed for ubuntu/wily64, but they get ubuntu/trusty64 closish to being viable.
#- name: Add repositories
#  command: 'apt-add-repository universe'
#  changed_when: false
#- name: Add repositories
#  command: 'apt-add-repository multiverse'
#  changed_when: false

- name: Ensure Entermedia gpg
  copy:
    src: files/entermediadb.gpg
    dest: /etc/apt/trusted.gpg.d/entermediadb.gpg
    owner: root
    group: root
    mode: 0644

- name: Ensure Entermedia repository
  apt_repository:
    repo: 'deb http://packages.entermediadb.org/repo/apt stable main'
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Ensure Entermedia group
  group:
    name: entermedia
    state: present

- name: Ensure Entermedia user
  user:
    name: entermedia
    group: entermedia
    state: present

- name: Install Entermedia DB with package manager (slow on new provision)
  apt:
    name: entermediadb
    state: present

- name: Copy the wrapper for the site install script
  copy:
    src: files/emdb-install.sh
    dest: /usr/bin/emdb-install.sh
    owner: root
    group: root
    mode: 0755

# Fix https://github.com/entermedia-community/entermediadb-installers/commit/25aaaf60e8420aa9cc3aa1b80b0b31ba5a0d775a
- name: BUG, Fix site install script bug part 1
  replace:
    dest: /usr/bin/entermediadb
    regexp: '}/webapp/\*"'
    replace: '}"/webapp/*'
- name: BUG, Fix site install script bug part 2
  replace:
    dest: /usr/bin/entermediadb
    regexp: 'webapp/WEB-INF/data/\*"'
    replace: 'webapp/WEB-INF/data/"*'

- stat: path=/opt/entermediadb
  register: site_installed_path

- name: Install a site instance of Entermedia
  shell: emdb-install.sh >> /var/log/emdb-log.txt
  when: site_installed_path.stat.exists == False

# Fix https://github.com/entermedia-community/entermediadb-installers/issues/1
- name: BUG, copy node.xml part 1
  command: cp /usr/share/entermediadb/webapp/WEB-INF/node.xml /opt/entermediadb/webapp/WEB-INF/node.xml
- name: BUG, copy node.xml part 2
  command: 'chown entermedia:entermedia /opt/entermediadb/webapp/WEB-INF/node.xml'

#- name: Set the JRE_HOME variable in the new application.
#  lineinfile:
#    dest: /opt/entermediadb/tomcat/bin/setenv.sh
#    line: 'export JRE_HOME=/usr/bin/java'

- name: Restart for apt updates on new box
  shell: 'sleep 2 && shutdown -r now "Restart new Ubuntu box"'
  async: 1
  poll: 0
  ignore_errors: true
  when: site_installed_path.stat.exists == False

- name: Restart entermedia after server restart
  command: '/opt/entermediadb/tomcat/bin/startup.sh'
  become_user: entermedia
